@GamesAPI_Host = http://localhost:5006/games

### Get All Games
GET {{GamesAPI_Host}}

### Get Game by Id
GET {{GamesAPI_Host}}/1

### Get Game by Id, Not Found
GET {{GamesAPI_Host}}/8

### Create New Game
POST {{GamesAPI_Host}}
Content-Type: application/json

{
  "name": "Forza Horizon 5",
  "genreId": 4,
  "price": 19.99,
  "releaseDate": "2023-05-19"
}

### Create New Game, Bad Request
POST {{GamesAPI_Host}}
Content-Type: application/json

{
  "name": "Forza Horizon 5 Forza Horizon 5 Forza Horizon 5 Forza Horizon 5 Forza Horizon 5 Forza Horizon 5 Forza Horizon 5 Forza Horizon 5 Forza Horizon 5 Forza Horizon 5",
  "price": 19.99,
  "releaseDate": "2023-05-19"
}

### Update Game by Id
PUT {{GamesAPI_Host}}/5
Content-Type: application/json

{
  "name": "Forza Horizon 4",
  "genreId": 4,
  "price": 9.99,
  "releaseDate": "2023-05-19"
}

### Update Game by Id, Not Found
PUT {{GamesAPI_Host}}/7
Content-Type: application/json

{
  "name": "Forza Horizon 5",
  "genre": "Racing",
  "releaseDate": "2023-05-19"
}

### Delete Game by Id
DELETE {{GamesAPI_Host}}/5

### Delete Game by Id, Not Found
DELETE {{GamesAPI_Host}}/9
